config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'signups#index'
  get 'fetch_shifts' => 'shifts#fetch_shifts'
  resources :signups
  resources :shifts

  post 'edit_request' => 'signups#edit_request'
  get 'contact' => 'pages#contact'
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :signup
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :user
end

app/models/shift.rb
class Shift < ActiveRecord::Base
  has_many :signups

  def available_spots?
    # return true if not enough people have signed-up
    self.required_number - self.signups.count > 0
  end

  def spots_remaining
    self.required_number - self.signups.count
  end

  def self.available_shift_ids
    # returns an array of ids for shifts with spots left to fill
    ids = []
    all.each do |shift|
      ids << shift.id if shift.spots_remaining > 0
    end
    ids
  end

end

app/models/shift_base.rb
class ShiftBase < ActiveRecord::Base
  self.abstract_class = true

  def self.available_shifts
    # broken: want to return any shifts where the required number of volunteers is greater than
    # the number of signups for that Shift.  Essentially shifts that aren't already filled up.
    self.joins(:signups).where(:required_people > self.signups)
  end
end

app/models/signup.rb
class Signup < ActiveRecord::Base
  belongs_to :shift
  has_many :messages

  validates :name, presence: true
  validates :email, presence: true
  validates :phone_number, presence: true
end

app/models/spreadsheet.rb
require 'csv'

class Spreadsheet
  def self.volunteer_spreadsheet
    package = Axlsx::Package.new
    wb = package.workbook

    Shift.all.each do |shift|
      wb.add_worksheet(name: shift.name) do |sheet|
        sheet.add_row %w{name email phone_number team_affiliation signup_id}
        shift.signups.each do |signup|
          sheet.add_row [signup.name, signup.email, signup.phone_number, signup.team_affiliation, signup.id]
        end
      end
    end
    ###
    ##
    package
  end

  def self.team_volunteers
    package = Axlsx::Package.new
    wb = package.workbook
    team_roster = []
    CSV.foreach(Rails.root.join('lib/racer_roster.csv')) do |row|
      next if row[1] == 'First Name'
      first = row[1]
      last = row[2]
      team_roster << "#{first.try(:capitalize)} #{last.try(:capitalize)}"
    end
    team_roster.sort!

    wb.add_worksheet(name: 'volunteers') do |sheet|
      sheet.add_row %w{TEAM SHIFT NAME SBR_TEAM_MEMBERS}
      count = 0
      Signup.all.order('name ASC').each do |signup|
        sheet.add_row [signup.team_affiliation, signup.shift.name, signup.name, team_roster[count]]
        count += 1
      end
    end
    package
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :roles

  def admin?
    self.roles.include?(Role.where(name: 'admin').first)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end
end

app/controllers/shifts_controller.rb
# Once again this is not being used
#
# class ShiftsController < ApplicationController
#
#   def fetch_shifts
#     @new_signup = Signup.new
#     @shift_type = params[:shift_type].to_s
#     if @shift_type == 'all'
#       @shifts = Shift.all
#     else
#       @shifts = Shift.where(shift_type: @shift_type)
#     end
#     respond_to do |format|
#       format.html { render 'signups/index'}
#       format.js
#     end
#   end
# end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  before_action :set_signup, only: [:show, :edit, :update, :destroy]
  before_action :new_signup, only: [:index, :show, :new, :create]
  respond_to :html, :js

  # GET /signups
  # GET /signups.json
  def index
    if params[:shift_type]
      @shift_type = params[:shift_type].to_s
      if params[:shift_type] == 'all_available'
        @shifts = Shift.where(id: Shift.available_shift_ids).order(:display_order)
      else
        @shifts = Shift.where(shift_type: @shift_type).order(:display_order)
      end
    else
      @shifts = Shift.all.order(:display_order)
      @shift_type = 'all'
    end
  end

  def edit_request
    signup = Signup.find(params[:signup_id])
    request = { name: params[:name], message: params[:message] }
    if VolunteerMailer.edit_request_email(signup, request).deliver_now
      flash[:notice] = 'Message Sent, I\'ll get back to you as soon as I can'
      Message.create(sender_name: request[:name], sender_email: signup.email, message: request[:message], signup_id: signup.id)
    else
      flash[:error] = 'an error occurred when trying to send message'
    end
    redirect_to :back
  end

  # GET /signups/1
  # GET /signups/1.json
  def show
  end

  # GET /signups/new
  def new
  end

  # GET /signups/1/edit
  def edit
  end

  # POST /signups
  # POST /signups.json
  def create
    @signup = Signup.new(signup_params)
    @shift_type = Shift.find(@signup.shift_id).shift_type
    @shifts = Array(Shift.find(@signup.shift_id))

    respond_to do |format|
      if @signup.save
        flash.now[:notice] = 'Successfully signed up'
        format.html { render :index }
        # format.html { redirect_to :back, notice: 'Successfully signed up' }
        # format.json { render :show, status: :created, location: @signup }
        format.js
      else
        format.html { render :index }
        format.json { render json: @signup.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /signups/1
  # PATCH/PUT /signups/1.json
  def update
    respond_to do |format|
      if @signup.update(signup_params)
        format.html { redirect_to @signup, notice: 'Signup was successfully updated.' }
        format.json { render :show, status: :ok, location: @signup }
      else
        format.html { render :edit }
        format.json { render json: @signup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /signups/1
  # DELETE /signups/1.json
  def destroy
    @signup.destroy
    respond_to do |format|
      format.html { redirect_to signups_url, notice: 'Signup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def new_signup
      @new_signup = Signup.new
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_signup
      @signup = Signup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def signup_params
      params.require(:signup).permit(:name, :email, :phone_number, :shift_id, :team_affiliation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Volunteer Signup</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= favicon_link_tag 'sbr_favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= image_tag 'sbr_logo_wt_rough.png' %>
        <%= image_tag 'lucky_pie_crit_white.png' %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to 'Home', root_path, class:'active' %></li>
          <li><%= link_to 'Race Flyer', '/2017_lucky_pie_crit_flyer.pdf' %></li>
          <!--<li><%#= link_to 'Contact', contact_path %></li>-->
        </ul>
        <% if current_user %>
          <ul class="nav navbar-nav pull-right">
            <li id="user"><%= current_user.email %></li>
            <li><%= link_to '', destroy_user_session_path, method: :delete, class:'fa fa-sign-out fa-2x' %></li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav pull-right">
            <li><%= link_to 'Sign-in', new_user_session_path %></li>
          </ul>
        <% end %>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/pages/contact.html.erb
<h3 id="contact">Contact</h3>
<hr>
<div class="contact-form">
  <div class="contact-form-header">
    <h4>If you have any general questions, let us know.</h4>
  </div>
  <%= form_tag do %>
      <%= text_field_tag :name, nil, placeholder: 'name' %>
    <br>
      <%= email_field_tag :email, nil, placeholder: 'email' %>
    <br>
      <%= text_area_tag :message, nil, size: '50x10' %>
      <%= submit_tag 'Send Message', class: 'btn btn-default' %>
  <% end %>
</div>

app/views/shared/_edit_email_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="edit-signup-modal" tabindex="-1" role="dialog" aria-labelledby="editEmailModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h5 class="modal-title" id="editEmailModal">Email the volunteer coordinator to change your signup</h5>
      </div>
      <div class="modal-body">

        <p>
          In order to keep track of things we need to be aware of any changes, issues, or conflicts that come up.<br>
          To this end, only the volunteer coordinator can make changes to the sign-up sheet.  So if you need to make a change
          just drop us a line with this form.  Thanks!
        </p>
        <div class="edit-modal-form">
          <%= form_tag({controller: 'signups', action: 'edit_request'}, method: :post) do %>
            <%= hidden_field_tag(:signup_id) %>
            <%= label_tag :name, 'Name:', id: 'name-label' %>
            <%= text_field_tag(:name) %>
              <br/>
            <div class="modal-text-area">
              <%= label_tag :message, 'Message:' %><br>
              <%= text_area_tag(:message, '', size: '50x10') %>
            </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

        <!-- Have the button post to a 'mailer' endpoint which grabs param values-->
          <%= submit_tag 'Send Message', class: 'btn btn-primary' %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_shift_table.html.erb
<!-- establish local variable within partial of 'shifts' -->
<% shifts.each do |shift| %>
  <div class="row">
    <h3><%= "#{shift.name} -- #{shift.shift_time}" %></h3>
    <% if current_user.try(:admin?) %>
      <p class="admin-info text-muted"><%= "shift_type: #{shift.shift_type} - id: #{shift.id}" %></p>
    <% end %>

    <div class="shift-table" id="shift-<%= shift.id %>">
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>No.</th>
            <th>Name</th>
            <th>Phone</th>
            <th>Email</th>
            <th>Team Affiliation</th>
          </tr>
        </thead>
        <tbody>
          <% shift.signups.each_with_index do |signup, i| %>
            <tr>
              <td><%= i + 1 %></td>
              <td><%= signup.name %></td>
              <td><%= signup.phone_number %></td>
              <td><%= signup.email %></td>
              <td>
                <%= signup.team_affiliation || 'none' %>
                <button class="btn btn-default btn-sm fa fa-envelope pull-right"  data-toggle="modal"
                        data-signup-id="<%= signup.id %>" data-target="#edit-signup-modal"></button>
              </td>

              <% if current_user.try(:admin?) %>
                <td style="width: 5%;">
                  <%= link_to 'Edit', edit_signup_path(signup) %>
                  <%= link_to 'Delete', signup, method: :delete, data: { confirm: 'Are you sure?' } %>
                </td>
              <% end %>
            </tr>
          <% end %>
          <% if shift.available_spots? %>
            <% (shift.spots_remaining - 1).times do |i| %>
              <% num = shift.signups.count + (i + 1) %>
              <tr>
                <td><%= num %></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
              </tr>
            <% end %>
            <!-- inline form for signups with new_signup passed as a local variable -->
            <tr>
              <%= form_for @new_signup do |f| %>
                  <%= f.hidden_field :shift_id, value: shift.id %>
                  <td><%= shift.required_number %></td>
                  <td><%= f.text_field :name, placeholder: 'name' %></td>
                  <td><%= f.text_field :phone_number, placeholder: 'phone: 970-555-1000' %></td>
                  <td><%= f.email_field :email, placeholder: 'email address' %></td>
                  <td>
                    <%= f.text_field :team_affiliation, placeholder: 'team affiliation' %>
                    &nbsp;<%= f.submit 'Sign Up', class: 'btn btn-default' %>
                  </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<hr>
<% end %>

app/views/shifts/fetch_shifts.js.erb
// returns shifts based on params[:shift_type]

$('#shifts-table').html("<%= j (render 'shared/shift_table', shifts: @shifts) %>");
// make the tab associated with these shifts active
$('.shift-button').removeClass('active');
$("#<%= @shift_type %>-tab").addClass('active');

app/views/signups/_form.html.erb
<%= form_for(@signup) do |f| %>
  <% if @signup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@signup.errors.count, "error") %> prohibited this signup from being saved:</h2>

      <ul>
      <% @signup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :team_affiliation %><br>
    <%= f.text_field :team_affiliation %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/signups/edit.html.erb
<h1>Editing Signup</h1>

<%= render 'form' %>

<%= link_to 'Show', @signup %> |
<%= link_to 'Back', signups_path %>

app/views/signups/fetch_shifts.js.erb
$('#shifts-table').html("<%= j (render 'shared/shift_table', shifts: @shifts) %>");
// make the tab associated with these shifts active
$('.shift-buttons').removeClass('active');
$("#<%= @shift_type %>-tab").addClass('active');

console.log(<%= @shift_type %>);

app/views/signups/index.html.erb
<h1>Volunteer Signup Shifts</h1>

<%= link_to 'All Shifts', signups_path,
            :'data-no-turbolink' => true, class: 'btn btn-default shift-button active', id: 'all-tab' %>
<%= link_to 'All Available', signups_path(shift_type: 'all_available'),
            :'data-no-turbolink' => true, class: 'btn btn-default shift-button', id: 'all_available-tab' %>
<%= link_to 'Before Race-day / Race-day Setup', signups_path(shift_type: 'setup'),
            :'data-no-turbolink' => true, class: 'btn btn-default shift-button', id: 'setup-tab' %>
<%= link_to 'Marshall', signups_path(shift_type: 'marshall'),
            :'data-no-turbolink' => true, class: 'btn btn-default shift-button', id: 'marshall-tab' %>
<%= link_to 'Registration', signups_path(shift_type: 'registration'),
            :'data-no-turbolink' => true, class: 'btn btn-default shift-button', id: 'registration-tab' %>
<%= link_to 'Breakdown / Day After', signups_path(shift_type: 'breakdown'),
            :'data-no-turbolink' => true, class: 'btn btn-default shift-button', id: 'breakdown-tab' %>

<hr>
<% if @signup && @signup.errors.any? %>
  <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4><i class="fa fa-exclaimation-triangle fa-2x"></i>Sign up unsuccessful becuase...</h4>
    <% @signup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
  </div>

<% end %>

<div id="shifts-table">
  <%= render 'shared/shift_table', shifts: @shifts %>
</div>
<%= render 'shared/edit_email_modal' %>
<br>

<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    $('.shift-button').removeClass('active');
    $('#<%= @shift_type %>-tab').addClass('active');

    <% if flash[:shift_id] %>
      var position = $(<%= escape_javascript "#shift-#{flash[:shift_id]}" %>).position();
      $(window).scrollTop(position.top);
    <% end %>
  });

  // insert the signup_id into a hidden field in the modal
  $('#edit-signup-modal').on('show.bs.modal', function(e) {
    var signupId = $(e.relatedTarget).data('signup-id');
    $(e.currentTarget).find('input[name="signup_id"]').val(signupId);
  });
</script>

app/views/signups/new.html.erb
<h1>New Signup</h1>

<%= render 'form' %>

<%= link_to 'Back', signups_path %>

app/views/signups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @signup.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @signup.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @signup.phone_number %>
</p>

<p>
  <strong>Team Affiliation:</strong>&nbsp;
  <%= @signup.team_affiliation %>
</p>

<%= link_to 'Edit', edit_signup_path(@signup) %> |
<%= link_to 'Back', signups_path %>

app/views/signups/tab_index.html.erb
<!-- assume you recieve @shifts and @signups from controller -->
<div>
  <h1>Volunteer Signups</h1>
  <p>*You must sign up for at least two volunteer shifts. See the <%= link_to 'race flyer' %> if you'd like to race and avoid conflicts</p>
</div>
<br>

<div>
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <% @shifts.each do |shift| %>
      <li role="presentation" class="tab">
        <a href=<%= "#shift_#{shift.id}" %> aria-controls=<%= "#shift_#{shift.id}" %> role="tab" data-toggle="tab">
          <%= shift.name %>
        </a>
      </li>
    <% end %>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <% @shifts.each do |shift| %>
      <div role="tabpanel" class="tab-pane fade" id=<%= "shift_#{shift.id}" %> >
        <h2><%= "#{shift.name} -- #{shift.shift_time}" %></h2>
        <% if current_user.try(:admin?) %>
            <p class="admin-info text-muted"><%= "shift_type: #{shift.shift_type} -- id: #{shift.id}"%></p>
        <% end %>
        <%= render 'shared/shift_table', shift: shift %>
      </div>
    <% end %>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    $('li.tab').first().addClass('active');
    $('.tab-pane').first().addClass('in active');
  });
</script>